// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACHzVCUmBSyZYIhkybbIbFz9Efa14QvBY',
    appId: '1:680369484973:web:7a50eacce509178dd28224',
    messagingSenderId: '680369484973',
    projectId: 'fstore-ff348',
    authDomain: 'fstore-ff348.firebaseapp.com',
    storageBucket: 'fstore-ff348.appspot.com',
    measurementId: 'G-F12SSZGMT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKAOrec4-pKO3kJykqsRHHMt1W-zzmL2Y',
    appId: '1:680369484973:android:11d7835a0c978c15d28224',
    messagingSenderId: '680369484973',
    projectId: 'fstore-ff348',
    storageBucket: 'fstore-ff348.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEGjBH0sPQCJpmlol1WiHSv-LU5VCcUDM',
    appId: '1:680369484973:ios:03f3f2473e815286d28224',
    messagingSenderId: '680369484973',
    projectId: 'fstore-ff348',
    storageBucket: 'fstore-ff348.appspot.com',
    iosBundleId: 'com.example.gloceryAppWithAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEGjBH0sPQCJpmlol1WiHSv-LU5VCcUDM',
    appId: '1:680369484973:ios:fcc54aa3dd74ba5ed28224',
    messagingSenderId: '680369484973',
    projectId: 'fstore-ff348',
    storageBucket: 'fstore-ff348.appspot.com',
    iosBundleId: 'com.example.gloceryAppWithAdmin.RunnerTests',
  );
}
